services:
  - type: web
    name: magicpin-vera-bot
    env: python
    buildCommand: "echo 'No dependencies to install!'"
    startCommand: "python bot.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: PORT
        value: 8080
      - key: LLM_PROVIDER
        sync: false
      - key: LLM_API_KEY
        sync: false
      - key: LLM_MODEL
        sync: false
